### ISSUE TITLE
The bot does not playing some streams on YouTube

### ISSUE THREAD

**Issue by GrieVeR-13** [Stardust-Discord/Octave#56]
**Describe the bug**
The Octave bot cannot play my streams on YouTube.
I read the sources of lavaplayer, the problem is in the headers of fragments of the mp4 format.  This happens when YouTube returns the mpeg file with no sidx header. 

**To Reproduce**
Not work: https://www.youtube.com/watch?v=KVbHBto_lwk
Work: https://www.youtube.com/watch?v=5qap5aO4i9A

**Comment by Devoxin** [comment]
Unfortunately this issue is out of scope for the bot. However your digging does appear very intriguing and could perhaps be useful [upstream](https://github.com/sedmelluq/lavaplayer/issues), as that would be our best way of getting a solution -- Lavaplayer doesn't (easily) offer the ability to patch issues like these.
